<?php
echo '<h1>'.$this->translate($this->title).'</h1>';

if ($this->action =='creation') {
	
	echo $this->form;
	
	
	?>
	<style>
	.cke_editable {
		background-color:#f9f9f9;
	}
	</style>
	
	<script type="text/javascript" >
	
	jQuery(document).ready( function() {
				<?php if ($this->hasHtml) {?>
					//Rich Text for iTop version 2.3.
			 		$( 'textarea#description' ).ckeditor({
			 		    language: 'fr',
	
			 		  // extraPlugins: 'uploadimage,image',
						//height: 300,
	
						// Upload images to a CKFinder connector (note that the response type is set to JSON).
						//uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json',
	
						// Configure your file manager integration. This example uses CKFinder 3 for PHP.
						/*
						filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
						filebrowserImageBrowseUrl: '/ckfinder/ckfinder.html?type=Images',
						filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
						filebrowserImageUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
						filebrowserImageUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
						*/
	
						filebrowserBrowseUrl : '/kcfinder/browse.php?opener=ckeditor&type=files',
						filebrowserImageBrowseUrl : '/kcfinder/browse.php?opener=ckeditor&type=images',
						filebrowserFlashBrowseUrl : '/kcfinder/browse.php?opener=ckeditor&type=flash',
						filebrowserUploadUrl : '/kcfinder/upload.php?opener=ckeditor&type=files',
						filebrowserImageUploadUrl : '/kcfinder/upload.php?opener=ckeditor&type=images',
						filebrowserFlashUploadUrl : '/kcfinder/upload.php?opener=ckeditor&type=flash',
						
						// The following options are not necessary and are used here for presentation purposes only.
						// They configure the Styles drop-down list and widgets to use classes.
	
						stylesSet: [
							{ name: 'Narrow image', type: 'widget', widget: 'image', attributes: { 'class': 'image-narrow' } },
							{ name: 'Wide image', type: 'widget', widget: 'image', attributes: { 'class': 'image-wide' } }
						],
						
						// Load the default contents.css file plus customizations for this sample.
						contentsCss: [ CKEDITOR.basePath + 'contents.css', 'http://sdk.ckeditor.com/samples/assets/css/widgetstyles.css' ],
	
						// Configure the Enhanced Image plugin to use classes instead of styles and to disable the
						// resizer (because image size is controlled by widget styles or the image takes maximum
						// 100% of the editor width).
						image2_alignClasses: [ 'image-align-left', 'image-align-center', 'image-align-right' ],
						image2_disableResizer: true
	
				 		    });
					<?php }?>
	});
</script>
	
<?php 
	
	}
else
	{?>
		
		<table style = "width:100%;">
		<tr>
		<td>
		<p> <?php echo $this->translate('Votre demande a bien été enregistrée sous la référence');?><b> <?php echo $this->ref_request;?></b></p> 
		<p> <?php echo $this->translate('Vous recevrez très bientôt un mail vous rappelant la référence votre demande.');?></p>
		<p><?php echo $this->translate('L\'équipe de support vous remercie.');?></p>
		

		</td>
		<td>
		<a class="more" href="<?php echo $this->url(array('controller' => 'openedrequest', 'action' => 'index', 'module' => 'request','ref_request'=>null), 'default'); ?>"><?php echo $this->translate('Consulter la liste des incidents');?></a>
		<br>
		<a class="more" href="<?php echo $this->url(array('controller' => 'newrequest', 'action' => 'index', 'module' => 'request','ref_request'=>null), 'default'); ?>"><?php echo $this->translate('Nouvelle déclaration d\'incident');?></a>
		</td>
		</tr>
		</table>
		
<?php }?>

<script type="text/javascript" >
$(function(){ // wait for document to load 
 $('#tab_files-0').MultiFile({ 
  STRING: {
   file: '<em title="Click to remove" onclick="$(this).parent().prev().click()">$file</em>',
   remove: '<img src="/layouts/frontoffice/images/delete-icon.png" height="16" width="16" alt="x"/>'
  }
 }); 
});
</script>