<?php 
$this->headScript()->appendFile('/layouts/backoffice/js/highcharts/excanvas.js');
$this->headScript()->appendFile('/layouts/backoffice/js/highcharts/highcharts.js'); 

$this->placeholder('body_id')->set('tpl-dashboard');
$this->placeholder('headling_1')->set(sprintf('<h1>%s</h1>', $this->translate('Hey %s, what’s up?', Centurion_Auth::getCurrent()->username)));

?>

<div class="col-right"></div>
<div class="col-left" style="clear:right;">
    <?php echo $this->placeholder('glance'); ?>
</div>

<div class="clear"><br/><br/></div>

<div class="clear">&nbsp;</div>