<?php
echo '<h1>'.$this->translate($this->title).' '.$this->ref.'</h1>';

if ($this->typ == 'view' OR $this->typ == 'maj') {
	?>


	
	
 
	<?php
	if (is_array($this->request))
	{
		$data = $this->request;
		echo '<TABLE class="gridtable">';
		echo '<tr>';
		echo '<td class="half">';
			echo '<TABLE class="gridtable">';
			echo '<tr>';
			echo '<td class="title"><b>'.$this->translate('Référence').'</b></td>';
			echo '<td class="content">'.$data['ref'].'</td>';
			echo '</tr>';
			echo '<tr>';
			echo '<td class="title"><b>'.$this->translate('Caller').'</b></td>';
			echo '<td class="content">'.$data['caller_id_friendlyname'].'</td>';
			echo '</tr>';
			/*echo '<tr>';
			echo '<td class="title"><b>'.$this->translate('Location').'</b></td>';
			echo '<td class="content">'.$data['site_name'].'</td>';
			echo '</tr>';*/
			echo '<tr>';
			echo '<td class="title"><b>'.$this->translate('Service').'</b></td>';
			echo '<td class="content">'.$data['service_name'].'</td>';
			echo '</tr>';
			echo '<tr>';
			echo '<td class="title"><b>'.$this->translate('Title').'</b></td>';
			echo '<td class="content">'.$data['title'].'</td>';
			echo '</tr>';
			echo '<tr>';
			echo '<td class="title"><b>'.$this->translate('Description').'</b></td>';
			echo '<td class="content">'.$data['description'].'</td>';				
			echo '</tr>';
			echo '</TABLE>';
		echo '</td>';
		
		echo '<td class="half">';
			echo '<TABLE class="gridtable">';
			echo '<tr>';
			echo '<td class="title"><b>'.$this->translate('Status').'</b></td>';
			echo '<td class="content">'.$data['status'].'</td>';
			echo '</tr>';
			echo '<tr>';
			echo '<td class="title"><b>'.$this->translate('Priority').'</b></td>';
			echo '<td class="content">'.$data['priority'].'</td>';
			echo '</tr>';
			echo '<tr>';
			echo '<td class="title"><b>'.$this->translate('Request Type').'</b></td>';
			echo '<td class="content">'.$data['request_type'].'</td>';
			echo '</tr>';
			echo '<tr>';
			echo '<td class="title"><b>'.$this->translate('Hot Flag').'</b></td>';
			echo '<td class="content">-</td>';
			echo '</tr>';
			echo '<tr>';
			echo '<td class="title"><b>Start Date</b></td>';
			echo '<td class="content">'.$data['start_date'].'</td>';
			echo '</tr>';
			echo '<tr>';
			echo '<td class="title"><b>'.$this->translate('Resolution Date').'</b></td>';
			echo '<td class="content">'.$data['resolution_date'].'</td>';
			echo '</tr>';
			echo '<tr>';
			echo '<td class="title"><b>'.$this->translate('Last Update').'</b></td>';
			echo '<td class="content">'.$data['last_update'].'</td>';
			echo '</tr>';
			echo '<tr>';
			echo '<td class="title"><b>'.$this->translate('Agent').'</b></td>';
			echo '<td class="content">'.$data['agent_id_friendlyname'].'</td>';
			echo '</tr>';
			echo '</TABLE>';
		echo '</td>';
		echo '</tr>';
		echo '</table>';
	
		//echo $this->translate('Public Log');
		if (is_array($this->attached_files))
			{if (count($this->attached_files)> 0)
				{
					echo '<h4>Pièces attachées au Ticket</h4>';
					echo '<ul class="attachment">';
					foreach ($this->attached_files as $key => $attach)
					{
						$mimetype = $attach->_mimetype;
						if ($attach->_filetype=='image') { $preview_class = 'preview';}
						else {$preview_class = '';}
						echo '<li class="attachment"><a class="'.$preview_class.'" href="'.
								$this->url(array('controller' => 'closedrequest', 'action' => 'download', 'module' => 'request','attachedfile_index'=>$key,'attach_id'=>$attach->_id,'filename'=>$attach->_filename), 'default') .'"target="_blank">'.
								$attach->_filename.
								//' - '.$attach->_id.
								'</a></li>';
					}
					echo '</ul>';
					echo '<br>';
				}
			}	
			
	
		//echo $this->updateRequestForm;
		
			?>
			<script type="text/javascript" >
				$(function(){ // wait for document to load 
				 $('#tab_files-0').MultiFile({ 
				  STRING: {
				   file: '<em title="Click to remove" onclick="$(this).parent().prev().click()">$file</em>',
				   remove: '<img src="/layouts/frontoffice/images/delete-icon.png" height="16" width="16" alt="x"/>'
				  }
				 });

				/*Config */
				xOffset = 10;
				yOffset = 30;
				
				// these 2 variable determine popup's distance from the cursor
				// you might want to adjust to get the right result
					
				/* END CONFIG */
				$("a.preview").hover(function(e){
					this.t = this.title;
					this.title = "";	
					var c = (this.t != "") ? "<br/>" + this.t : "";
					$("body").append("<p id='preview'><img style='max-height:300px;' src='"+ this.href +"' alt='Prévisualisation' />"+ c +"</p>");	
					//$("body").append("<p id='preview'><iframe src='"+ this.href +"' alt='Prévisualisation' /></iframe>"+ c +"</p>");
												 
					$("#preview")
						.css("top",(e.pageY - xOffset) + "px")
						.css("left",(e.pageX + yOffset) + "px")
						.fadeIn("fast");						
			    },
				function(){
					this.title = this.t;	
					$("#preview").remove();
			    });	
				$("a.preview").mousemove(function(e){
					$("#preview")
						.css("top",(e.pageY - xOffset) + "px")
						.css("left",(e.pageX + yOffset) + "px");
				});		

					  
			});
		</script>
		
		<script type="text/javascript">
		 $(document).ready( function() {
			    $('#accordion').accordion({
			        collapsible:true,
			        heightStyle: "content",
			        beforeActivate: function(event, ui) {
			             // The accordion believes a panel is being opened
			            if (ui.newHeader[0]) {
			                var currHeader  = ui.newHeader;
			                var currContent = currHeader.next('.ui-accordion-content');
			             // The accordion believes a panel is being closed
			            } else {
			                var currHeader  = ui.oldHeader;
			                var currContent = currHeader.next('.ui-accordion-content');
			            }
			             // Since we've changed the default behavior, this detects the actual status
			            var isPanelSelected = currHeader.attr('aria-selected') == 'true';
			            
			             // Toggle the panel's header ( ui-state-active devient  ui-state pour ne pas mettre en blanc et ne pas toucher au css
			            currHeader.toggleClass('ui-corner-all',isPanelSelected).toggleClass('accordion-header-active ui-state-active ui-corner-top',!isPanelSelected).attr('aria-selected',((!isPanelSelected).toString()));
			            
			            // Toggle the panel's icon
			            currHeader.children('.ui-icon').toggleClass('ui-icon-triangle-1-e',isPanelSelected).toggleClass('ui-icon-triangle-1-s',!isPanelSelected);
			            
			             // Toggle the panel's content
			            currContent.toggleClass('accordion-content-active',!isPanelSelected)    
			            if (isPanelSelected) { currContent.slideUp(); }  else { currContent.slideDown(); }
		
			            return false; // Cancels the default action
			        }
			    });
			});
	</script>
		
		<?php 
		//echo $this->form;
		echo '</div>';
		
		echo '<div id="accordion">';
		arsort($data['public_log']['entries']);
		foreach ($data['public_log']['entries'] as $log)
		{ 
			echo '<h2>'.$log['user_login'].' a écrit le '.$log['date'].':</h2>';
			$order   = array("\r\n", "\n", "\r");
			$replace = '<br />';
			echo '<p>'.str_replace($order, $replace,$log['message']). '</p>'; 
		}
		echo '</div>';		
	}
	
}

else {
	
	$this->placeholder('undermenu')->captureStart();
	?>
 		<script type="text/javascript">
		$(document).ready(function() {

			var ajaxManager = (function() {
			     var requests = [];
			     return {
			        addReq:  function(opt) {
			            requests.push(opt);
			        },
			        removeReq:  function(opt) {
			            if( $.inArray(opt, requests) > -1 )
			                requests.splice($.inArray(opt, requests), 1);
			        },
			        run: function() {
			            var self = this,
			                oriSuc;
			            if( requests.length ) {
			                oriSuc = requests[0].complete;

			                requests[0].complete = function() {
			                     if( typeof(oriSuc) === 'function' ) oriSuc();
			                     requests.shift();
			                     self.run.apply(self, []);
			                };   
			                $.ajax(requests[0]);
			            } else {
			              self.tid = setTimeout(function() {
			                 self.run.apply(self, []);
			              }, 1000);
			            }
			        },
			        stop:  function() {
			            requests = [];
			            clearTimeout(this.tid);
			        }
			     };
			}());

			ajaxManager.run(); 
			
			$(".USER_LOCATION").dropdownchecklist( { icon: {}, width: 150 ,firstItemChecksAll: true } );
			$(".USER_YEAR").dropdownchecklist( { icon: {}, width: 150 ,firstItemChecksAll: true } );

			$( '#<?php echo $this->OPref->_ParamName_UserFilter?>' ).change(function (){
				var isChecked = $('#<?php echo $this->OPref->_ParamName_UserFilter?>').is(':checked');
				launchAjax('<?php echo $this->OPref->_ParamName_UserFilter?>',isChecked);
				}
			);

			$( '#<?php echo $this->OPref->_ParamName_UserLocation?>' ).change(function() {
				//alert($('#<?php echo $this->OPref->_ParamName_UserLocation?>').val());
				launchAjax('<?php echo $this->OPref->_ParamName_UserLocation?>',$('#<?php echo $this->OPref->_ParamName_UserLocation?>').val());
		  	});

		  	$( '#<?php echo $this->OPref->_ParamName_UserYear?>' ).change(function() {
				//alert($('#<?php echo $this->OPref->_ParamName_UserYear?>').val());
				launchAjax('<?php echo $this->OPref->_ParamName_UserYear?>',$('#<?php echo $this->OPref->_ParamName_UserYear?>').val());
		  	});


		  	$('#submitbutton').click(function(){
				 //alert('Ref :'+ ref.value+', Titre :'+title.value+', Description :'+description.value);
				 launchAjax2(ref.value,title.value, description.value, public_log.value,date_started.value,date_closed.value);
			  });


		  	
			
			 function launchAjax(param,value){
					$.ajax({
					//ajaxManager.addReq({
						//async : false,
						//url       : '/user/preference/changepref',
						url       : '/request/closedrequest/index/language/<?php echo $this->OPref->_language;?>',
						type      : 'post',
						dataType : 'html',
						data      :{
							'searchMode' : 'false',
							'user_id' : '<?php  echo $this->OPref->_user_id;?>',
							'param' : param,
							'value' : value,
							'sessid' : '<?php echo session_id();?>'
							},
						success : function(data){
							//alert(data);
							//$('#grille').dataTable().fnDestroy();
							//$('#grille').append(data);
							
							$('#grille').empty();
							$('#grille').append(data);
							
							
							//$('#grille').dataTable();
														
							},
						error :function(xhr, ajaxOptions, thrownError){
							alert(xhr.status);
							alert(thrownError);
						},
						complete : function(data){
							//$('#grille').empty();
							//$('#grille').append(data);
							
						}		
					});
				}


			 function launchAjax2(ref,title, description, public_log, date_started, date_closed){
					$.ajax({
						url       : '/request/closedrequest/index/language/<?php echo $this->OPref->_language;?>',
						type      : 'post',
						dataType : 'html',
						data      :{
							'searchMode' : 'true',
							'ref' : ref,
							'title' : title,
							'description' : description,
							'public_log' : public_log,
							'start_date' : date_started,
							'close_date' : date_closed
							},
						success : function(data){
							//alert(data);
							//$('#grille').dataTable().fnDestroy();
							$('#grille').empty();
							$('#grille').append(data);
							//$('#grille').dataTable();
														
							},
						error :function(xhr, ajaxOptions, thrownError){
							alert(xhr.status);
							alert(thrownError);
						},
						complete : function(data){
							//alert(data);
						}		
					});
				}

		});
		
		</script>	

 	
	<?php 
	echo $this->form;
	$this->placeholder('undermenu')->captureEnd();
	
	?>
	
	
	 <style>
		.toggler {}
		
		#SearchModule {text-align:center;
					margin-top: -23px;}
		
		#button { /*padding: .5em 1em; text-decoration: none;*/
		
		background:url('/layouts/frontoffice/images/BT_expand.png');}
		#effect { padding: 0.4em; position: relative; }
		#effect h3 { margin: 0; padding: 0.4em; text-align: center; font-weight:normal; }
		#effect p { margin: 0; padding: 0.4em; text-align: left; }
		
		table.SearchModule {margin:auto;}
		table.SearchModule td { padding : 5px;}
		table.SearchModule td.BTSearch { text-align:center;}
		table.SearchModule th { padding: 5px;
								text-align : right;}
	</style>
	<script>
	 $(function() {
		// run the currently selected effect
		function runEffect() {
		// get effect type from
		var selectedEffect = $( "#effectTypes" ).val();
		// most effect types need no options passed by default
		var options = {};
		// some effects have required parameters
		if ( selectedEffect === "slide" ) {
		options = { percent: 0 };
		} else if ( selectedEffect === "size" ) {
		options = { to: { width: 200, height: 60 } };
		}
		// run the effect
		$( "#effect" ).toggle( 'blind', options, 500 );
		};
		// set effect from select menu value
		$( "#button" ).click(function() {
		runEffect();
		});

		<?php
		//if (!($this->SearchModuleOpen)) 
		{ echo '$( "#effect" ).hide();';}
		?>
		});
	</script>
	
	<style type="text/css">
		dt {float:left;
			margin-left : 5px;
			margin-right : 5px;
			display:inline; 
			}
		dd {float:left;}
	</style>
	
	<div id="SearchModule" >
		<div class="toggler">
			<div id="effect" class="ui-widget-content ui-corner-all">
			<h3 class="ui-widget-header ui-corner-all">Recherche</h3>
			<div id="frm" style="text-align:left;">
			<?php echo $this->SearchFrm;?>
			</div>
			</div>
		</div>
	
		
		<img src="/layouts/frontoffice/images/BT_expand.png" id="button"/>
	</div>	
 	
 	<style type="text/css">
		/*pour eviter que les filtres dépassent en bas*/
		section .content{
			min-height:420px; 
			}
			
		table {
		    table-layout:fixed;
		}
		td{
		    overflow:hidden;
		    text-overflow: ellipsis;
		}
	</style>
	
	
	<?php 
	
	
	echo '<div id="datagrid">';
	echo '<script type="text/javascript">'.$this->script.'</script>';
	echo $this->tableau;
	echo '</div>';
	
} 


?>
