<?php
$this->headTitle('It Works');
$this->placeholder('body_id')->set('install-complete');
$this->headLink()->appendStylesheet('/layouts/frontoffice/css/intro.css');
?>


<div class="wrap">

	<div class="header">
		<h1>
			<a href="/"> iTop's Portal - Front Office </a>
		</h1>
		
			<span class="slogan"><h1> iTop's Portal	</h1></span>
	

		<h1>
			<a class="partner" href="/" style="float: right;"> iTop's Portal -
				Front Office </a>
		</h1>

	</div>
	<div class="clear"></div>
	<div class="shadow-top"></div>
	
		<h1 class="heading-1">Congratulations guy, all cables are connected !</h1>
			<div class="left">
				<span class="btn-inner"> <a class="btn" href="/home"> <span
						class="btn-text">Enter the machine as User</span>
				</a>
				</span> 
				<br /> <br /> 
				<div class="credential">Login: <b>dali@demo.com</b><br /> Password: <b>Salvador1234</b><br />
				</div>
			</div>
			<div class="right">	
				
				<span class="btn-inner"> <a class="btn" href="/admin"> <span
						class="btn-text">Enter the machine as Admin</span>
				</a>
				</span> <br /> <br /> 
				<div class="credential">Login: <b>admin</b><br /> Password: <b>admin1234</b><br />
				</div>
			</div>
			<div class="clear"></div>

	<div class="bottom">
		<h2>To Know More :</h2>
		<ul class="doc-list">
			<li class="doc-list-1">
				<ul>
					<li class="doc-list-2"><a
						href="#">Access to 2 differents iTop</a>
						<p>One Portal to access to 2 iTop, one production and one testing version for example.
						The 2 iTop must have the same version number.</p>
					</li>

					<li class="doc-list-2"><a
						href="#">Use Ldap</a>
						<p>It's possible to use Ldap for authentication on the portal. The configuration parameters will be store
						in the <b>application.ini</b> file.</p>
					</li>
				</ul>
			</li>
			<li class="doc-list-1">
				<ul>
					<li class="doc-list-2"><a
						href="#">Import User from iTop</a>
						<p>You're using the iTop default portal ? After installing this portal, you will be able to import 
						all portal users defined in iTop. Only the password will be reseted to the default value <em>first_name</em>1234 </p>
					</li>

					<li class="doc-list-2"><a
						href="#">Services Desk</a>
						<p>After configuring your services and subcategories services on iTop, you can choose pictures to 
						illustrate them into your Services Desk at the home page.</p>
					</li>
				</ul>
			</li>

			<li class="doc-list-1">
				<ul>
					<li class="doc-list-2"><a
						href="#">Translation
							trait</a>
						<p>A little "How To" to implement the translation module in your
							module</p>
					</li>
					<li class="doc-list-2"><a
						href="http://wiki.centurion-project.org/Develop_with_Centurion/The_view_layer">The
							View layer</a>
						<p>As in a normal Zend Framework application, the view files are
							.pthml files they are placed into the a view folder inside the
							scripts sub-folder.</p>
					</li>
				</ul>
			</li>
		</ul>

		<div class="clear"></div>
	</div>
	<div class="shadow-bottom"></div>
</div>
