
<h1>Gestion des Services</h1>
 <p>La page d'accueil du site liste les services proposés aux clients. Ces services peuvent être de 2 types :
 <ul>
 <li class="list">Des services issus de iTop et récupérés via le Webservices. On importe donc le service / élement de service de iTop, on le personnalise 
 via la configuration dans le panneau d'administration (choix de l'icône et de la couleur associée). La liste est donc dépendante des services
 renseignés dans iTop.</li>
 <li class="list">Des services configurés localement configurés de façon à pointer vers un triplet Module/Controller/Action. Le style est actuellement codé dans le CSS.</li>
 </ul>
