<style>
#loading{
position: relative; /* on positionne le conteneur */
  margin-left: auto;
  margin-right: auto;
  width: 100%;
  text-align: center;
  margin-top:80px;
  }
</style>

<?php $this->ShowAlerts();?>
 

<div id="loading">
<img src="/layouts/frontoffice/images/Loading.gif" style="height:150px;"/></div>
<div id="dash">
<ul id="myDashboard"></ul>
</div>

<script type="text/javascript">
$(document).ready(function() {	
			DoTheJob();
	});

	function DoTheJob(){
			//First : db.ini file generation to store the database credentials
			$.ajax({ 
	    		type: "POST",
	            url: "<?php echo $this->url;?>",
	            data: {
					},
				success: function(data){
					$('#loading').fadeOut(500, function() {
					   //$(this).empty().show();
					   $.getScript(data);
					   $("#dash").append(data);
					   $("#dash").hide();
					   $("#dash").fadeIn(500);
					});
		       }
		   });
}
	
</script>