<?php

echo '<h1>'.$this->translate('Vos Contacts').'</h1>';

echo '<h2>'.$this->translate('Le responsable').'</h2>';
echo '<ul>';
foreach ($this->leader as $member) {
	echo '<li class="list">'.$member['first_name'].' '.$member['name'].', '.$member['description'].'</li>';
}
echo '</ul>';
echo '<br>';

echo '<h2>'.$this->translate('Les membres de l\'équipe').'</h2>';

echo '<ul>';
foreach ($this->team as $member) {
	echo '<li class="list">'.$member['first_name'].' '.$member['name'].', '.$member['description'].'</li>';
}
echo '</ul>';
?>



<?php //echo $this->form;?>