<?php
$this->gridForm()->addHeader($this->form, array(
    'elements' =>  array('name'),
));

$this->gridForm()->addMain($this->form, array(
    'label'         => 'Alert informations',
    'description'   => 'Alert informations',
    'elements'      => array('text',
                             'organizations') //,
    						//'alerts')
));

$this->gridForm()->addAside($this->form, array(
    'label'     => 'Publication',
    'elements'  => array('is_active',
                         'start',
                         'stop',
    					'type',
    					'priority')
));

echo $this->partial('grid/_form.phtml', $this);