<?php
//Color defition for the graphic
$this->color = '#1C94C4';
echo '<h1>'.$this->translate('Tableau de bord').'</h1>';
echo '<h2>'.$this->translate('Les incidents ouverts sur l\'année écoulée').'</h2>';

 //Zend_Debug::dump($this->tableau);
  ?>

 <script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
		[<?php echo $this->translate("'Mois - Année'").','. $this->translate("'Nbre de tickets'");?>],
         <?php
    	$i=0;
		foreach($this->tableau as $key => $value) {
			if ($i>0) {echo ',';}
			//echo '[\''.$result['DATE_FORMAT(ticket.start_date, \'%M-%Y\')'].'\','.$result['COUNT(*)'].']';
			//echo '[\''.$result['mois'].'\','.$result['total'].']';
			echo '[\''.$key.'\','.$value.']';
			$i++;
		}
		?>
        ]);

       var options = {
          title: <?php echo $this->translate("'Tickets par mois'");?>,
		  titleTextStyle:{color: '<?php echo $this->color;?>', fontName: 'Calibri', fontSize:16},
          hAxis: {title: <?php echo $this->translate("'Mois - Année'")?>,  colors: 'red',
					fontName: 'Arial', 
					fontSize: 10,
					titleTextStyle: {color: '<?php echo $this->color;?>'}},
		  chartArea:{left:45,top:20,width:"100%",height:"70%"},
		  colors: ['<?php echo $this->color;?>'],
		   animation:{duration:5000,easing: 'out',}
				
        };

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
  </head>
  <body>
    <div id="chart_div" style="width: 700px; height: 300px;"></div>
<br>
<p><?php echo $this->translate('Le graphique ci-dessus donne la répartition des tickets incidents déclarés les mois passés.');?></p>



     

