<Style>
div#SrvDesc {
	float:left;
	margin-left:-35px;
}
section aside {
    margin: 0px;
    margin-top:20px;
    float: right;
    width: 250px;
    z-index: 1;
    background: none repeat scroll 0% 0% rgba(0, 0, 0, 0.25);
	padding: 0px 15px 0px;
	color: #FFF;
}
#fieldset-Servicerequest dt#eltsrvdesc-label{
background:url("/layouts/frontoffice/images/info_verysmall.png") no-repeat  transparent;
background-position : 95%;
height: 32px;
}
 #fieldset-Servicerequest dd#eltsrvdesc-element{
/*background: none repeat scroll 0% 0% rgba(0, 0, 0, 0.3);
	color: #FFF;
	width:75%;*/
	font-size:80%;
}
</Style> 
<?php

switch ($this->page) {
	case "ClientServices" :
		echo $this->partial('catalogue/_clientServices.phtml', $this);
		break;
	case "iTopServices" :
		echo $this->partial('catalogue/_itopServices.phtml', $this);
		break;
	case "EltService" :
		echo $this->partial('catalogue/_eltServices.phtml', $this);
			break;
	case "FrmEltService" :
		echo $this->partial('catalogue/_frmEltServices.phtml', $this);
		break;
	case "TplFrmEltService" :
		echo $this->partial('catalogue/_tplFrmEltServices.phtml', $this);
		break;
	case "ValidForm" :
		echo $this->partial('catalogue/_validForm.phtml', $this);
		break;
	case "" :
		echo 'Oups, there is a problem !';
		break;
}
?>

<script type="text/javascript" >
$(function(){ // wait for document to load 
 $('#tab_files-0').MultiFile({ 
  STRING: {
   file: '<em title="Click to remove" onclick="$(this).parent().prev().click()">$file</em>',
   remove: '<img src="/layouts/frontoffice/images/delete-icon.png" height="16" width="16" alt="x"/>'
  }
 }); 
});
</script>
