<?php 
    $baseUrl = $this->baseUrl();
    $this->headLink()->appendStylesheet($baseUrl.'/layouts/backoffice/styles.css');
    /*$this->headScript()->appendFile($baseUrl.'/layouts/backoffice/js/all.js')
                       ->prependFile($baseUrl.'/cui/libs/jquery-ui.js')
                       ->prependFile($baseUrl.'/cui/libs/jquery.js');*/
?>
<!DOCTYPE html>
<html>
<head>
    <!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <?php echo $this->headTitle() ?>
    <base href="<?php echo $baseUrl; ?>/" />
    <?php echo $this->headLink() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headStyle() ?>
    <?php $this->jQuery()->enable(); 
        echo $this->jQuery(); ?>
    
    <?php echo $this->headScript() ?>
	
    
    <META http-equiv="Cache-Control" content="no-cache">
    <META http-equiv="Pragma" content="no-cache">
    <META http-equiv="Cache" content="no store">
    <META http-equiv="Expires" content="0">
    <script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	  ga('create', 'UA-42203148-2', 'shost.ca');
	  ga('send', 'pageview');
	</script>
</head>
	<body <?php if($this->placeholder('body_id')!= '') echo 'id="'.$this->placeholder('body_id').'"'; ?>
	<?php if($this->placeholder('body_onload')!= '') echo 'onload="'.$this->placeholder('body_onload').'"'; ?>  
	<?php if($this->placeholder('body_class') != '') echo 'class="'.$this->placeholder('body_class').'"'; ?>>
 
   	<div class="progress" id="progress" role="progressbar" >
		<div class="progress__bar" style="width:0%"><span class="progress__label"></span></div>
	</div>
  	
    <script type="text/javascript">
    jQuery(document).ready(function($){
         $('.progress').asProgress({
            'namespace': 'progress', 
	    });
	  });
    </script>
	<section class="login-box-frame">
		<div class="company_logo"></div>
	 	<?php echo $this->layout()->content ?>
	</section>
	<footer class="login">
	    <a href="http://emmanuel.synology.me" title="About me" target="_blank">
	    Emmanuel's website</a>
	    <a href="http://www.combodo.com" title="Combodo" target="_blank" style="float:left;margin-left:15px;"> 
	    iTop</a>
	</footer>
	</body>
</html>