  <!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>It works!</title>
        <?php 
        $this->headLink()->appendStylesheet('/layouts/backoffice/styles.css');
        $this->headLink()->appendStylesheet('/layouts/frontoffice/css/intro.css');
        $this->headLink()->appendStylesheet('/cui/theme/css/tipsy.css');
        $this->headScript()->appendFile('/cui/libs/jquery.js');
        $this->headScript()->appendFile('/layouts/backoffice/js/all.js');
        $this->headScript()->appendFile('/cui/plugins/utils/jquery.tipsy.js');
        
        echo $this->headScript();
       	echo $this->headLink();
        
        ?>
        <!--[if IE]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
      
    </head>


 <body<?php if($this->placeholder('body_id')!= '') :
        echo ' id="'.$this->placeholder('body_id') . '"'; 
     endif;
     if($this->placeholder('body_class') != '') 
		{echo ' class="'.$this->placeholder('body_class').'"';} ?>>
  
  <?php echo $this->layout()->content ?>
</body>
</html>