 <?php echo $this->headLink() ?>
  <?php $this->jQuery()->enable(); 
        echo $this->jQuery(); ?>
 <?php //echo $this->headScript() ?>
 
 <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42200833-8', 'auto');
  ga('send', 'pageview');

</script>
 
 <body <?php if($this->placeholder('body_id')!= '') echo 'id="'.$this->placeholder('body_id').'"'; ?>
	<?php if($this->placeholder('body_onload')!= '') echo 'onload="'.$this->placeholder('body_onload').'"'; ?>  
	<?php if($this->placeholder('body_class') != '') echo 'class="'.$this->placeholder('body_class').'"'; ?>>
	
	 <section class="login-box">
	 <?php echo $this->layout()->content;?>
	 </section>
	 
	 
</body>	 
