<?php 
$this->placeholder('undermenu')->captureStart();
?>
 		<script type="text/javascript">
 		jQuery(document).ready(function() {
 			jQuery(".USER_LOCATION").dropdownchecklist( { icon: {}, width: 150 ,firstItemChecksAll: true } );
 			jQuery(".USER_YEAR").dropdownchecklist( { icon: {}, width: 150 ,firstItemChecksAll: true } );
 			jQuery( '#<?php echo $this->OPref->_ParamName_UserFilter?>' ).change(function() {
				var isChecked = $('#<?php echo $this->OPref->_ParamName_UserFilter?>').is(':checked');
				launchAjax('<?php echo $this->OPref->_ParamName_UserFilter?>',isChecked);
			  });
 			jQuery( '#<?php echo $this->OPref->_ParamName_UserLocation?>' ).change(function() {
				//alert($('#<?php echo $this->OPref->_ParamName_UserLocation?>').val());
				launchAjax('<?php echo $this->OPref->_ParamName_UserLocation?>',jQuery('#<?php echo $this->OPref->_ParamName_UserLocation?>').val());
		  	});
 			jQuery( '#<?php echo $this->OPref->_ParamName_UserYear?>' ).change(function() {
				//alert($('#<?php echo $this->OPref->_ParamName_UserYear?>').val());
				launchAjax('<?php echo $this->OPref->_ParamName_UserYear?>',jQuery('#<?php echo $this->OPref->_ParamName_UserYear?>').val());
		  	});
            function launchAjax(param,value){
				 jQuery.ajax({
						//url       : '/user/preference/changepref',
						url       : '/request/openedrequest/index/language/<?php echo $this->OPref->_language;?>',
						type      : 'post',
						dataType : 'html',
						data      :{
							'user_id' : '<?php  echo $this->OPref->_user_id;?>',
							'param' : param,
							'value' : value
							},
						success : function(data){
							//alert(data);
							//$('#grille').dataTable().fnDestroy();
							jQuery('#grille').empty();
							jQuery('#grille').append(data);
							//$('#grille').dataTable();
														
							},
						error :function(xhr, ajaxOptions, thrownError){
							alert(xhr.status);
							alert(thrownError);
						},
						complete : function(data){
						}		
					});
				}
		});
		
		</script>	

 		
 <?php 
	echo $this->form;
	$this->placeholder('undermenu')->captureEnd();
	
	echo '<div id="datagrid">';
	echo '<script type="text/javascript">'.$this->script.'</script>';
	echo $this->tableau;
	echo '</div>';
	?>